version: "3.9"

services:
    database_brainny:
        image: postgres
        container_name: database_brainny
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=teste
            - POSTGRES_PASSWORD=teste
            - POSTGRES_DB=teste
        volumes:
            - pgdata:/data/postgres


volumes:
    pgdata:
        driver: local
